# pg_restore --verbose --clean --no-acl --no-owner -h localhost -d nextread_development latest.dump

development: &development
  # POSTGRESQL
  adapter: postgresql
  database: chainreactor_development
  host: localhost

test: &TEST
  <<: *development
  database: chainreactor_test